Release fix (#3)
An initial attempt at adding a build and release pipeline was added to master, it didn't work.

This PR has investigated how we can get what we want.

* Build a single executable for linux and macos
    * On a pushed tag
    * Only works if tag is on master
    * Requires release notes to exist
* Create a github release and upload the executables as assets

This PR also adds some initial documentation

* Commented out lint and tests to speed things up
* allowing releases on any branch temporarily
* Moved to using maintained action for doing the release
* Adding permissions to write release contents
* Now executable names won't clash
* Removed windows as an option
* Fixed renaming the executable so that it is available for the release process
* Updated to tar up executable instead of renaming it
* added missing dash in asset name
* added requirement for release notes
* added dummy release notes
* added dummy release notes (fixed filename)
* added dummy release notes (fixed dirname in workflow)
* Revert "Commented out lint and tests to speed things up"
This reverts commit b16664c514a239da2e1db141de6bb21d97f29fd9.
* disabled tests and linting as working on releasing only
* fixed directory structure for release-notes
* Fixed handling of release body
* should now fail if release tag isn't on main
* Added initial documentation
* Removed dummy release-notes
* Revert "disabled tests and linting as working on releasing only"
This reverts commit aa325b081eb4f1e5c49ca779dcac9cb47db17f1c.
* Added release notes for first release
* Added content of developer guide

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,28 +2,48 @@ name: Build and Release
 
 on:
   push:
-    branches:
-      - master
     tags:
       - 'v*'
+
+permissions:
+  contents: write
 
 jobs:
   build:
     runs-on: ${{ matrix.os }}
     strategy:
       matrix:
-        os: [ubuntu-latest, macos-latest, windows-latest]
-        python-version: ['3.8']  # Specify your Python version
+        os: ['ubuntu-22.04', macos-12]
+        python-version: ['3.11']
         include:
-          - os: windows-latest
-            executable_extension: .exe
-          - os: ubuntu-latest
-            executable_extension: ''
-          - os: macos-latest
-            executable_extension: ''
+          - os: 'ubuntu-22.04'
+            executable_extension: -linux
+          - os: macos-12
+            executable_extension: -macos
 
     steps:
     - uses: actions/checkout@v3
+      with:
+        fetch-depth: 0
+
+    - name: Assert Tag is on Main Branch
+      run: |
+        TAG_COMMIT=$(git rev-list -n 1 ${{ github.ref }})
+        MASTER_COMMIT=$(git rev-list -n 1 origin/main)
+        if [ "$TAG_COMMIT" != "$MASTER_COMMIT" ]; then
+          echo "Tag is not on main branch. Stopping workflow."
+          exit 1
+        fi
+
+    - name: Assert Release Notes Present
+      id: release_notes
+      run: |
+        RELEASE_NOTES_FILE="docs/release-notes/${GITHUB_REF#refs/tags/}.md"
+        if [ ! -f "$RELEASE_NOTES_FILE" ]; then
+          echo "Release notes $RELEASE_NOTES_FILE not found."
+          exit 1
+        fi
+        echo "RELEASE_NOTES_FILE=$RELEASE_NOTES_FILE" >> $GITHUB_ENV
 
     - name: Set up Python
       uses: actions/setup-python@v4
@@ -41,29 +61,20 @@ jobs:
     - name: Build Executable
       run: pyinstaller --onefile adr/adr.py
 
-    - name: Determine Executable Name
-      run: echo "EXECUTABLE_NAME=adr${{ matrix.executable_extension }}" >> $GITHUB_ENV
+    - name: Tar up executable and announch filename
+      run: |
+        ASSET_NAME=adr-${{ matrix.os }}.tar.gz
+        cd dist
+        tar -czvf $ASSET_NAME adr
+        echo "ASSET_NAME=$ASSET_NAME" >> $GITHUB_ENV
 
-    - name: Create Release (only on ubuntu-latest)
-      if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-latest'
-      id: create_release
-      uses: actions/create-release@v1
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        tag_name: ${{ github.ref_name }}
-        release_name: Release ${{ github.ref_name }}
-        draft: false
-        prerelease: false
-
-    - name: Upload Release Asset
+    - name: Release
+      uses: softprops/action-gh-release@v1
       if: startsWith(github.ref, 'refs/tags/')
-      uses: actions/upload-release-asset@v1
+      with:
+        files: |
+          ./dist/${{ env.ASSET_NAME }}
+        body_path: ${{ env.RELEASE_NOTES_FILE }}
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      with:
-        upload_url: ${{ needs.create_release.outputs.upload_url }}
-        asset_path: ./dist/${{ env.EXECUTABLE_NAME }}
-        asset_name: ${{ env.EXECUTABLE_NAME }}
-        asset_content_type: application/octet-stream
-
+  
